name: Build Magisk Module

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up NDK environment
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: Build with NDK
      run: |
        cd module
        ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk

    - name: Package Magisk Module
      run: |
        cd ..
        zip -rZ9 ZygiskIl2CppDumper.zip module/*

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ZygiskIl2CppDumper
        path: ZygiskIl2CppDumper.zip
