name: Build Zygisk Il2CppDumper

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the target game (e.g. com.mobile.legends.usa)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: ${{ github.event.inputs.package_name }}

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle

    - name: Make gradlew executable and patch package name
      run: |
        chmod +x ./gradlew
        sed -i "s/moduleDescription = \"/moduleDescription = \"(${PACKAGE_NAME}) /g" module.gradle
        sed -i "s/com.game.packagename/${PACKAGE_NAME}/g" module/src/main/cpp/game.h

    - name: Build Module
      run: ./gradlew :module:assembleRelease

    - name: Upload Zygisk Module Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ZygiskIl2CppDumper
        path: out/magisk_module_release/
